### ISSUE TITLE
[D003] Versão Inicial do GDD

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#11]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D003_Versao_Inicial_do_GDD.md

**Comment by jpbusche** [comment]
https://github.com/IJE-CryingDino/Traveling_Will/wiki/GDD

**Comment by edsomjr** [comment]
João,

é isso mesmo. Tem um erro ou outro de digitação: faça uma leitura completa e corrija o que encontrar. Também é bom passar um corretor ortográfico antes dos commit que ajuda a pegar estes pontos.
