### ISSUE TITLE
[D004] GDD - Requisitos Tecnológicos

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#12]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D004_GDD_Requisitos_Tecnologicos.md

**Comment by jpbusche** [comment]
https://github.com/IJE-CryingDino/Traveling_Will/wiki/GDD#5-requisitos-tecnol%C3%B3gicos
