### ISSUE TITLE
[D006] GDD - Telas

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#14]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D006_GDD_Telas.md

**Comment by jpbusche** [comment]
https://github.com/IJE-CryingDino/Traveling_Will/wiki/GDD#6-telas
Professor Edson, as imagens referentes as telas são só exemplos, não significa que realmente a utilizaremos no jogo, quando o pessoal de design passar as imagens certa, mudaremos.
