### ISSUE TITLE
[D011] Sistema de Pontuação

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#19]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D011_Sistema_de_Pontuacao.md

**Comment by jpbusche** [comment]
https://github.com/IJE-CryingDino/Traveling_Will/wiki/GDD#9-sistema-de-pontua%C3%A7%C3%A3o
Professor Edson, as imagens referentes as telas são só exemplos, não significa que realmente a utilizaremos no jogo, quando o pessoal de design passar as imagens certa, mudaremos.
