### ISSUE TITLE
[D013] Principais Personagens do Mundo do Jogo

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#21]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D013_Principais_Personagens_do_Mundo_do_Jogo.md

**Comment by jpbusche** [comment]
https://github.com/IJE-CryingDino/Traveling_Will/wiki/GDD#11-personagens-do-mundo-do-jogo

**Comment by joao18araujo** [comment]
Professor, houve alguma falta nessa _issue_? Ela não foi fechada junto com as outras anteriormente fechadas.
