### ISSUE TITLE
[G006] Low-Fi Sketches

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#23]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G006_Low_Fi_Sketches.md

**Comment by joao18araujo** [comment]
O _commit_ que adiciona os _low-fi sketches_ é esse: [6f017ce](https://github.com/IJE-CryingDino/Traveling_Will/commit/6f017ce565e990bd64376e8df67be034d187f6a6)
