### ISSUE TITLE
[G007] Hi-Fi Sketches

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#24]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G007_Hi_Fi_Sketches.md

**Comment by joao18araujo** [comment]
Professor, as _hi-fi sketches_ dos níveis e do Will podem ser encontradas nas pastas https://github.com/IJE-CryingDino/Traveling_Will/tree/master/res/1, https://github.com/IJE-CryingDino/Traveling_Will/tree/master/res/2, https://github.com/IJE-CryingDino/Traveling_Will/tree/master/res/3 e https://github.com/IJE-CryingDino/Traveling_Will/tree/master/res/will
