### ISSUE TITLE
[P003] Janela

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#25]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P003_Janela.md

**Comment by vitorbaraujo** [comment]
@edsomjr nos baseamos no que está sendo feito como teste na engine (pasta ijengine/test/) para a criação da janela. O commit que adiciona a criação da janela é esse: [7bc1973](https://github.com/IJE-CryingDino/Traveling_Will/commit/7bc197309596e5fd80b9a2d657d7e03261ee6c8a)

**Comment by edsomjr** [comment]
Vitor,

é preciso tomar cuidado, pois você está versionando a lib, que está compilada em 32 bits, e aqui que é 64 bits deu falha de segmentação. Tem que ou incluir ambas e tentar carregar dinamicamente a correta (para isso é preciso mexer na engine) ou colocar o código da lib e compilá-lo junto do jogo na hora do make (resolve no desenvolvimento, e não no deploy).

Mas por hora é isso mesmo, sigamos adiante.

**Comment by vitorbaraujo** [comment]
Percebemos esse descuido com a lib ontem a noite. Essa semana pensaremos numa solução.
