### ISSUE TITLE
[P004] Módulo de Vídeo

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#26]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P004_Modulo_de_Video.md

**Comment by vitorbaraujo** [comment]
Professor, não tenho certeza se é isso que esta issue pede, porém em relação a rotinas de baixo nível, foram utilizados retângulos (com imagens) no inicio da construção do jogo. Mais para frente, estes retângulos com as imagens (os low-fi sketches) foram substituídos pelos botões de fato e foram configuradas suas ações.
