### ISSUE TITLE
[P006] Tela de Apresentação

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#28]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P006_Tela_de_Apresentacao.md

**Comment by vitorbaraujo** [comment]
Professor, com este commit [(595fc62)](https://github.com/IJE-CryingDino/Traveling_Will/commit/595fc62e6a518afee46e8ad54e2df072de491d57) a implementação da tela de apresentação foi concluída, faltando apenas as imagens finalizadas pela equipe de design.

**Comment by edsomjr** [comment]
Vitor,

estou recebendo uma falha de segmentação ao executar o jogo de vocês.

**Comment by igorribeiroduarte** [comment]
Professor, acredito que agora corrigimos a falha de segmentação. Poderia rodar o jogo novamente?

**Comment by edsomjr** [comment]
Agora está ok.
