### ISSUE TITLE
[P007] Controles

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#29]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P007_Controles.md

**Comment by igorribeiroduarte** [comment]
Professor, com esse último commit [(8e65d4f)](https://github.com/IJE-CryingDino/Traveling_Will/commit/8e65d4fa07c16738a84f30ce73cffc67726a965d) implementamos inicialmente todos os controles principais.
