### ISSUE TITLE
[D016] Visão Geral do Mundo do Jogo

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#31]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D016_Visao_Geral_do_Mundo_do_Jogo.md

**Comment by jpbusche** [comment]
https://github.com/IJE-CryingDino/Traveling_Will/wiki/GDD#18-vis%C3%A3o-geral-do-mundo-do-jogo
