### ISSUE TITLE
[D023] Músicas e Efeitos Sonoros

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#38]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D023_Musicas_e_Efeitos_Sonoros.md

**Comment by joao18araujo** [comment]
https://github.com/IJE-CryingDino/Traveling_Will/wiki/GDD#16-m%C3%BAsicas-e-efeitos-sonoros
