### ISSUE TITLE
[G008] Músicas

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#39]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G008_Musicas.md

**Comment by joao18araujo** [comment]
Professor, as músicas dos níveis e do menu podem ser encontradas em https://github.com/IJE-CryingDino/Traveling_Will/tree/master/res/1, https://github.com/IJE-CryingDino/Traveling_Will/tree/master/res/2, https://github.com/IJE-CryingDino/Traveling_Will/tree/master/res/3 e https://github.com/IJE-CryingDino/Traveling_Will/tree/master/res/menu
