### ISSUE TITLE
[G003] Documento de Apresentação da Equipe

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#4]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G003_Documento_de_Apresentacao_da_Equipe.md

**Comment by joao18araujo** [comment]
https://github.com/IJE-Manaslu/Traveling_Will/wiki/Apresenta%C3%A7%C3%A3o-da-Equipe
