### ISSUE TITLE
[G010] Arte Definitiva

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#41]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G010_Arte_Definitiva.md

**Comment by joao18araujo** [comment]
Professor, a arte definitiva dos níveis, do Will e dos inimigos podem ser encontradas nas pastas https://github.com/IJE-CryingDino/Traveling_Will/tree/development/res/1, https://github.com/IJE-CryingDino/Traveling_Will/tree/development/res/2, https://github.com/IJE-CryingDino/Traveling_Will/tree/development/res/3, https://github.com/IJE-CryingDino/Traveling_Will/tree/development/res/4, https://github.com/IJE-CryingDino/Traveling_Will/tree/development/res/5, https://github.com/IJE-CryingDino/Traveling_Will/tree/development/res/6, https://github.com/IJE-CryingDino/Traveling_Will/tree/development/res/will e https://github.com/IJE-CryingDino/Traveling_Will/tree/development/res/enemies
