### ISSUE TITLE
[P008] Animações

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#42]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P008_Animacoes.md

**Comment by vitorbaraujo** [comment]
Em relação aos elementos que contém a cena estarem animados, isso acontece no limbo (seletor de fases), nas telas de finalização e no próprio jogo, onde o personagem, os coletáveis e os inimigos tem sprites animadas. A tela de game over foi implementada em [50c0db](https://github.com/IJE-CryingDino/Traveling_Will/commit/50c0dbc217ca21d93e84ab77ece0552d5f881990), onde é mostrada a tela quando o personagem colide com um inimigo atacável sem batê-lo ou um inimigo invencível. A tela de opções foi implementada em [4a504f](https://github.com/IJE-CryingDino/Traveling_Will/commit/4a504fbe4d73dd1efade3efe756091e45ac54144) e a tela de créditos foi implementada em [34685b](https://github.com/IJE-CryingDino/Traveling_Will/commit/34685bc8622fd0c47494366701899216fb8c97a5).
