### ISSUE TITLE
[P009] Gameplay

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#43]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P009_Gameplay.md

**Comment by igorribeiroduarte** [comment]
Professor, com esse commit (f418e45), após clicar em "Novo jogo" e selecionar a fase 1, é possível visualizar uma fase jogável, com os controles já implementados e uma versão parcial das imagens.
