### ISSUE TITLE
[P010] Textos

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#44]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P010_Textos.md

**Comment by vitorbaraujo** [comment]
O nosso jogo não conterá um módulo específico para textos e números. Ao invés disso, estão sendo utilizadas imagens com os textos relativos a botões e indicadores (tanto para quantidade de coletáveis quanto para quantidade de inimigos, entre outros). Essas imagens podem ser vistas com facilidade no menu e no indicador de coletáveis durante cada uma das fases.
