### ISSUE TITLE
[P011] Áudio

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#45]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P011_Audio.md

**Comment by vitorbaraujo** [comment]
Professor, os mecanismos de implementação do áudio se encontram na engine (devido aos pull requests feitos), a implementação da música de fundo das cenas do jogo e da tela de apresentação foram feitas em vários commits (como por exemplo, [f70b16](https://github.com/IJE-CryingDino/Traveling_Will/commit/f70b16090a72042a0f61bcb19d8e484b259dfb76), onde é configurado o áudio para a primeira fase). Em relação aos efeitos sonoros, estes foram implementados em [8d5e09](https://github.com/IJE-CryingDino/Traveling_Will/commit/8d5e09e8febf20edb5a294e9345ec9272d427f7c).
