### ISSUE TITLE
[P013] Primeira Fase Jogável

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#47]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P013_Primeira_Fase_Jogavel.md

**Comment by igorribeiroduarte** [comment]
Professor, com esse commit (1aa76fa), após clicar em "Continuar Aventura" e selecionar uma fase, é possível visualizar uma fase jogável, com todos os controles  e jogabilidade implementados.
