### ISSUE TITLE
[G004] Cronograma

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#5]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G004_Cronograma.md

**Comment by joao18araujo** [comment]
https://www.smartapp.com/gantterforgoogledrive/index.html?fileID=0ByqP27FNeiugY1p2UVlHRU40YUU

**Comment by edsomjr** [comment]
Caros,

não consigo visualizar o cronograma.

**Comment by joao18araujo** [comment]
Arrumamos o link.
