### ISSUE TITLE
[P002] Laço Principal

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#7]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P002_Laco_Principal.md

**Comment by vitorbaraujo** [comment]
O commit que adiciona o laço principal é esse: [7b96354](https://github.com/IJE-Manaslu/Traveling_Will/commit/7b96354b8b2ebb3a22538cf7cc3590b6562198e5)

**Comment by edsomjr** [comment]
Vitor,

o loop deve estar contido todo em um único método da classe main. Como isso será feito na engine, fecharemos esta issue por hora da forma que você fez mesmo.
