### ISSUE TITLE
[G005] Plano de Negócio

### ISSUE THREAD

**Issue by edsomjr** [IJE-CryingDino/Traveling_Will#8]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G005_Plano_de_Negocio.md

**Comment by joao18araujo** [comment]
https://github.com/IJE-Manaslu/Traveling_Will/wiki/Plano-de-Neg%C3%B3cio

**Comment by edsomjr** [comment]
João,

adicionei o ponto separador de milhar que ficou faltando em alguns valores e números na parte final do documento.
